version: "3"
services:
  zookeeper:
    image: "wurstmeister/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "wurstmeister/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=REQUESTS_TOPIC:1:1
      - KAFKA_MESSAGE_MAX_BYTES=600000000
      - KAFKA_SOCKET_REQUEST_MAX_BYTES=600000000
      - KAFKA_HEAP_OPTS=-Xmx2G
    depends_on:
      - zookeeper
  postgresDb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5455:5432"
    # volumes:
    #   - ./db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    links:
      - postgresDb
volumes:
  postgresDb:
    driver: local
